export const menuData = [
    {
  "id": "1",
  "name": "McDonald's",
  "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/08eee882fda81b68e5c36e3a5d89d8c0",
    "locality": "Main Street",
  coverimage: "https://www.mcdonalds.com/content/dam/sites/usa/nfl/publication/1PUB_Desktop_Deals-v1_1168x520.jpg",
  "areaName": "Downtown",
  "rating": 4.2,
  "timeToDeliver": 30,
  "menu": [
    { "id": 1, "item_name": "Big Mac", "price": 5.99, "description": "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.", "image": "https://b.zmtcdn.com/data/dish_photos/a36/66fc891f0259374e2f5b4ee5e9bcda36.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 2, "item_name": "McChicken", "price": 4.49, "description": "Breaded chicken patty, mayonnaise, shredded lettuce on a toasted bun.", "image": "https://b.zmtcdn.com/data/dish_photos/896/db46bfa6121525dc8bc4d7214ee29896.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 3, "item_name": "Filet-O-Fish", "price": 4.79, "description": "Delicious fish fillet, tartar sauce, and processed cheddar cheese on a steamed bun.", "image": "https://b.zmtcdn.com/data/dish_photos/1b3/4faf9dadf53fb18cd758dde429e151b3.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 4, "item_name": "French Fries", "price": 2.49, "description": "Golden, crispy, and seasoned with salt to perfection.", "image": "https://b.zmtcdn.com/data/dish_photos/1b3/4faf9dadf53fb18cd758dde429e151b3.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 5, "item_name": "Vanilla Cone", "price": 1.00, "description": "Creamy vanilla soft-serve ice cream in a crispy cone.", "image": "https://b.zmtcdn.com/data/dish_photos/59c/fff476db5b27f680e596f8baf43a759c.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 6, "item_name": "Apple Pie", "price": 1.29, "description": "Warm, flaky pastry filled with delicious cinnamon-spiced apple filling.", "image": "https://b.zmtcdn.com/data/dish_photos/b18/c8d9d045149d4c02263ccb2510fc1b18.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 7, "item_name": "Quarter Pounder with Cheese", "price": 6.49, "description": "Quarter-pound beef patty with cheese, onions, pickles, and mustard.", "image": "https://b.zmtcdn.com/data/dish_photos/2ac/03c10b0097d30e5fd485965c627d32ac.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 8, "item_name": "Chicken McNuggets", "price": 3.99, "description": "Bite-sized chicken pieces with a crispy coating.", "image": "https://b.zmtcdn.com/data/dish_photos/2ac/03c10b0097d30e5fd485965c627d32ac.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 9, "item_name": "McFlurry", "price": 2.99, "description": "Soft-serve ice cream blended with your favorite toppings.", "image": "https://b.zmtcdn.com/data/dish_photos/03d/c74108490c0ec3db9123681b90fa003d.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 10, "item_name": "Sausage McMuffin", "price": 3.49, "description": "Savory sausage patty on a toasted English muffin.", "image": "https://b.zmtcdn.com/data/dish_photos/197/f79dae360d566ed82db303516dc52197.jpg?output-format=webp" },
    { "id": 11, "item_name": "Hash Browns", "price": 1.49, "description": "Crispy fried potato patty.", "image": "https://www.allrecipes.com/thmb/3FXvOnlaER8gcmZA2X-SyjyU9Mo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/57783-emilys-famous-hash-browns-DDMFS-4x3-ce2a6ec1178640258faf601d6848ff11.jpg" },
    { "id": 12, "item_name": "Coca-Cola", "price": 1.00, "description": "Classic refreshing cola drink.", "image": "https://b.zmtcdn.com/data/dish_photos/058/be3adc62ae886b4d8e5f115bea9f7058.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 13, "item_name": "Double Cheeseburger", "price": 5.49, "description": "Two beef patties with melted cheese, pickles, onions, and ketchup.", "image": "https://b.zmtcdn.com/data/dish_photos/00b/3b90f00b79790328dc7e256aaea5900b.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 14, "item_name": "Egg McMuffin", "price": 3.99, "description": "Egg, cheese, and Canadian bacon on an English muffin.", "image": "https://b.zmtcdn.com/data/dish_photos/2c8/0c4185e53890f51e57a54bf70b9042c8.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" },
    { "id": 15, "item_name": "McDouble", "price": 2.99, "description": "Two beef patties, onions, pickles, and mustard.", "image": "https://b.zmtcdn.com/data/dish_photos/a45/ea3d317bb6ccfe3340634de11fcf5a45.png?output-format=webp&fit=around|130:130&crop=130:130;*,*" }
  ]
    },
    {
  "id": "2",
  "name": "Domino's Pizza",
      "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/hxoosforqtzk8vvtejiu",
  coverimage:"https://b.zmtcdn.com/data/pictures/chains/9/4000009/a0c3bcc09b1448a7138beda386f8db21.jpg?fit=around|771.75:416.25&crop=771.75:416.25;*,*",
  "locality": "M M Ali Jauhar Marg",
  "areaName": "New Friends Colony",
  "rating": 4.5,
  "timeToDeliver": 25,
  "menu": [
    { "id": 1, "item_name": "Margherita Pizza", "price": 10.99, "description": "Classic pizza with tomato sauce and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/39e8f7a1cb3398d997ce415cc86210db" },
    { "id": 2, "item_name": "Pepperoni Pizza", "price": 12.49, "description": "Pizza topped with pepperoni and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_1024/eb10d3bbeea43e9150307a8ebb32b220" },
    { "id": 3, "item_name": "Veggie Supreme Pizza", "price": 11.99, "description": "Loaded with assorted vegetables and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/4f3395d60363f951a7f9e2debbc352f2" },
    { "id": 4, "item_name": "Chicken BBQ Pizza", "price": 13.49, "description": "Delicious pizza with BBQ chicken and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/f7ef8df0fed856ee03c983f156fbb68d" },
    { "id": 5, "item_name": "Cheesy Garlic Bread", "price": 5.99, "description": "Breadsticks brushed with garlic butter and topped with cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/wfjxhqnswq8xcmivzcky" },
    { "id": 6, "item_name": "Pasta Primavera", "price": 9.99, "description": "Pasta with fresh vegetables in creamy sauce.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/8cba46bf669a7ca8946141eb7cc6882b" },
    { "id": 7, "item_name": "Choco Lava Cake", "price": 4.99, "description": "Warm chocolate cake with a gooey chocolate center.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/uc3oedg7ss4ryopigrtu" },
    { "id": 8, "item_name": "Paneer Tikka Pizza", "price": 12.99, "description": "Pizza topped with paneer tikka and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/81fbe5f6e8576cc7bdae699c3900197c" },
    { "id": 9, "item_name": "Chicken Golden Delight", "price": 13.49, "description": "Pizza with golden corn, double pepper barbecue chicken, and extra cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/62f3e2a1a523da9f291734686a75825b" },
    { "id": 10, "item_name": "Veg Extravaganza Pizza", "price": 12.99, "description": "Pizza loaded with a variety of vegetables and mozzarella cheese.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/1c5f2d5151e17a13d4d6e3cae89dfc63" },
    { "id": 11, "item_name": "Chicken Dominator", "price": 14.49, "description": "Pizza with grilled chicken rashers, double pepper barbecue chicken, and more.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/961822219e2fcbe797bb532c84bbcf14" },
    { "id": 12, "item_name": "Chicken Tikka Pizza", "price": 3.49, "description": "Spicy potato patty served in a bun with special sauce.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/90baa57b161d5dad43c3db433b8b8e25" },
    { "id": 13, "item_name": "Chicken Wings", "price": 6.99, "description": "Crispy and juicy chicken wings with your choice of sauce.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/iofnvxw1w6togleffnnm" },
    { "id": 14, "item_name": "Garlic Breadsticks", "price": 4.49, "description": "Breadsticks with a buttery garlic crust.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/nlysxha1a4tjdhyiqfiu" },
    { "id": 15, "item_name": "Farmhouse Pizza", "price": 11.99, "description": "Pizza topped with capsicum, onion, tomato, and more.", "image": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_208,h_208,c_fit/f7ef8df0fed856ee03c983f156fbb68d" }
  ]
    },
    {
  "id": "3",
  "name": "KFC",
      "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/56c9ab92bd79745fd152a30fa2525426",
  coverimage:"https://i.ytimg.com/vi/tMWtHH-L9yg/maxresdefault.jpg",
  "locality": "Main Street",
  "areaName": "Downtown",
  "rating": 4.0,
  "timeToDeliver": 35,
  "menu": [
    { "id": 1, "item_name": "Original Recipe Chicken", "price": 9.99, "description": "Finger-licking good, 11 herbs and spices chicken.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Crispy Chicken Strips", "price": 7.49, "description": "Tender and crispy chicken strips.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Zinger Burger", "price": 5.99, "description": "Spicy and crunchy chicken fillet burger.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Popcorn Chicken", "price": 4.99, "description": "Bite-sized juicy chicken pieces.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Mashed Potatoes", "price": 2.49, "description": "Creamy mashed potatoes with gravy.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Coleslaw", "price": 1.99, "description": "Classic coleslaw with cabbage and carrots.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Hot Wings", "price": 6.99, "description": "Spicy and crispy chicken wings.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Twister Wrap", "price": 6.49, "description": "Wrap with crispy chicken strips, lettuce, and mayo.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Bucket Meal", "price": 19.99, "description": "A bucket of chicken with sides and drinks.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "BBQ Chicken Burger", "price": 5.99, "description": "Grilled chicken burger with BBQ sauce.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Crispy Twister Wrap", "price": 6.99, "description": "Wrap with crispy chicken strips, lettuce, and spicy mayo.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Nuggets Meal", "price": 7.99, "description": "Chicken nuggets with sides and a drink.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Streetwise Feast", "price": 15.49, "description": "A feast with chicken, fries, and coleslaw.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "BBQ Wings", "price": 5.99, "description": "Tender chicken wings with BBQ sauce.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Potato Wedges", "price": 3.49, "description": "Seasoned and crispy potato wedges.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "4",
  "name": "Burger King",
      "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/e33e1d3ba7d6b2bb0d45e1001b731fcf",
  coverimage:"https://d1csarkz8obe9u.cloudfront.net/posterpreviews/burger-king-facebook-cover-design-template-d6a73eeb1990bf145fd9d7f016db7259_screen.jpg?ts=1654622682",
  "locality": "Broadway Avenue",
  "areaName": "City Center",
  "rating": 4.3,
  "timeToDeliver": 20,
  "menu": [
    { "id": 1, "item_name": "Whopper", "price": 8.99, "description": "Flame-grilled beef patty with lettuce, tomatoes, onions, and pickles.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Chicken Royale", "price": 7.49, "description": "Juicy chicken fillet burger with mayo and lettuce.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Veggie Burger", "price": 6.99, "description": "Vegetarian burger with fresh vegetables and mayo.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Crispy Chicken Sandwich", "price": 6.49, "description": "Crispy chicken fillet with lettuce and mayo.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "French Fries", "price": 2.49, "description": "Golden and crispy potato fries.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Onion Rings", "price": 3.49, "description": "Battered and fried onion rings.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Chicken Tenders", "price": 5.99, "description": "Tender and juicy chicken strips.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Cheeseburger", "price": 4.99, "description": "Classic burger with cheese, pickles, onions, and ketchup.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Double Whopper", "price": 10.99, "description": "Double flame-grilled beef patties with lettuce, tomatoes, onions, and pickles.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Crispy Chicken Salad", "price": 6.99, "description": "Crispy chicken strips on a bed of fresh lettuce and veggies.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "BBQ Bacon Double Cheeseburger", "price": 9.49, "description": "Double cheeseburger with BBQ sauce and bacon.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Big Fish Sandwich", "price": 7.49, "description": "Breaded fish fillet with tartar sauce and lettuce.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Bacon King", "price": 10.99, "description": "Flame-grilled beef patty with bacon, cheese, and mayo.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Chicken Fries", "price": 4.49, "description": "Crispy and elongated chicken strips.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Hamburger", "price": 3.99, "description": "Simple and classic hamburger with pickles and ketchup.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "5",
  "name": "Subway",
      "cloudinaryImageId": "https://image.cnbcfm.com/api/v1/image/107178410-1673614380134-gettyimages-1456044360-dsc_1531_2feb95eb-ffc0-4c85-9e01-70445ff5393a.jpeg?v=1682337706&w=1600&h=900",
  coverimage:"https://images.deliveryhero.io/image/fd-hk/LH/s2uv-hero.jpg",
  "locality": "Central Street",
  "areaName": "Midtown",
  "rating": 4.1,
  "timeToDeliver": 15,
  "menu": [
    { "id": 1, "item_name": "Italian B.M.T.", "price": 7.99, "description": "Spicy sandwich with Genoa salami, pepperoni, and ham.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Subway Club", "price": 7.49, "description": "Delicious sandwich with turkey, roast beef, and ham.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Veggie Delite", "price": 6.99, "description": "Vegetarian sandwich with fresh vegetables.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Roast Beef", "price": 7.49, "description": "Sub with tender and juicy roast beef.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Chicken Teriyaki", "price": 7.99, "description": "Chicken sub with sweet teriyaki sauce.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Meatball Marinara", "price": 6.49, "description": "Sub with meatballs and marinara sauce.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Tuna", "price": 6.99, "description": "Classic sub with creamy tuna salad.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Steak & Cheese", "price": 7.99, "description": "Sub with tender steak and melted cheese.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Spicy Italian", "price": 7.49, "description": "Sub with spicy pepperoni and salami.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Turkey Breast", "price": 6.49, "description": "Sub with lean and tender turkey breast.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Sweet Onion Chicken Teriyaki", "price": 7.99, "description": "Chicken sub with sweet onion sauce.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Buffalo Chicken", "price": 7.49, "description": "Sub with spicy buffalo chicken strips.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Black Forest Ham", "price": 6.49, "description": "Sub with Black Forest ham.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Oven-Roasted Chicken", "price": 6.99, "description": "Sub with tender oven-roasted chicken.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "B.L.T.", "price": 6.49, "description": "Sub with crispy bacon, lettuce, and tomatoes.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "6",
  "name": "Pizza Hut",
      "cloudinaryImageId": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_kx8Tj7x0Oe9IcHKe3hL0fz3YwJKRdWoY7w&usqp=CAU",
      coverimage: "https://image.adsoftheworld.com/vfdwd97goq3u73cnyloyaewsju1w",
  
  "locality": "Park Avenue",
  "areaName": "City Center",
  "rating": 4.4,
  "timeToDeliver": 25,
  "menu": [
    { "id": 1, "item_name": "Margherita Pizza", "price": 9.99, "description": "Classic pizza with tomato sauce, mozzarella cheese, and basil.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Pepperoni Pizza", "price": 11.49, "description": "Pizza topped with pepperoni and mozzarella cheese.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Veggie Supreme Pizza", "price": 10.99, "description": "Loaded with assorted vegetables and mozzarella cheese.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Chicken Supreme Pizza", "price": 12.49, "description": "Delicious pizza with chicken, onions, and mozzarella cheese.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Garlic Breadsticks", "price": 4.99, "description": "Breadsticks with a buttery garlic crust.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Pasta Alfredo", "price": 9.99, "description": "Pasta with creamy Alfredo sauce.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Stuffed Crust Pizza", "price": 13.99, "description": "Pizza with cheese-stuffed crust.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Hawaiian Pizza", "price": 11.99, "description": "Pizza with ham and pineapple toppings.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Meat Lovers Pizza", "price": 12.99, "description": "Pizza with a variety of meat toppings and mozzarella cheese.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Supreme Pizza", "price": 12.99, "description": "Pizza loaded with various toppings and mozzarella cheese.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Chicken Wings", "price": 7.99, "description": "Crispy and juicy chicken wings with your choice of sauce.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Tuscani Pasta", "price": 11.49, "description": "Pasta with your choice of sauce and toppings.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Cheese Pizza", "price": 9.99, "description": "Pizza with delicious melted cheese.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Cinnabon Mini Rolls", "price": 5.49, "description": "Sweet mini rolls with Cinnabon flavor.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Cheesy Bites Pizza", "price": 13.99, "description": "Pizza with bite-sized cheese-filled crust.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "7",
  "name": "Baskin Robbins - Ice Cream Desserts",
  "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/85ccae4e3576f9330af102c46ca85395",
  "locality": "Main Street",
      "areaName": "Downtown",
  coverimage:"https://logo.com/image-cdn/images/kts928pd/production/a10e0f2b7fbc01703d3b3665bdcbec648c9ee5a2-1000x563.png?w=1080&q=72",
  "rating": 4.5,
  "timeToDeliver": 20,
  "menu": [
    { "id": 1, "item_name": "Vanilla Ice Cream", "price": 3.99, "description": "Classic creamy vanilla ice cream.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Chocolate Chip Cookie Dough", "price": 4.49, "description": "Vanilla ice cream with chocolate chip cookie dough chunks.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Mint Chocolate Chip", "price": 4.49, "description": "Mint-flavored ice cream with chocolate chips.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Pralines 'n Cream", "price": 4.99, "description": "Vanilla ice cream with caramel praline swirls.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Chocolate Fudge Brownie", "price": 4.49, "description": "Chocolate ice cream with fudge brownie chunks.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Rainbow Sherbet", "price": 3.99, "description": "Assorted fruit-flavored sherbets.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Strawberry Cheesecake", "price": 4.99, "description": "Strawberry ice cream with cheesecake bits.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Caramel Turtle Truffle", "price": 4.99, "description": "Caramel ice cream with chocolate truffles and caramel swirls.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Jamoca Almond Fudge", "price": 4.49, "description": "Coffee-flavored ice cream with chocolate-covered almonds.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Cookie Dough Delight", "price": 4.99, "description": "Chocolate ice cream with cookie dough and chocolate chunks.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Mango Tango", "price": 3.99, "description": "Mango-flavored ice cream with real mango pieces.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Black Currant", "price": 3.99, "description": "Rich black currant-flavored ice cream.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Rocky Road", "price": 4.49, "description": "Chocolate ice cream with marshmallows and nuts.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Butter Pecan", "price": 4.49, "description": "Butter-flavored ice cream with pecan pieces.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Cherry Jubilee", "price": 3.99, "description": "Cherry-flavored ice cream with cherries.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "8",
  "name": "Natural Ice Cream",
  "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/c8b98c4064dc2fd6bdf350212e5f0bd5",
  "locality": "Green Street",
      "areaName": "Midtown",
  coverimage:"https://b.zmtcdn.com/data/pictures/chains/4/91784/d7d11466e85c31bb241acac61c73eaa6.jpg",
  "rating": 4.7,
  "timeToDeliver": 25,
  "menu": [
    { "id": 1, "item_name": "Tender Coconut Ice Cream", "price": 4.99, "description": "Refreshing ice cream made with tender coconut.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Alphonso Mango Ice Cream", "price": 5.49, "description": "Luscious ice cream with Alphonso mango flavor.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Sitaphal Ice Cream", "price": 5.49, "description": "Creamy ice cream made with Sitaphal (custard apple).", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Chikoo Ice Cream", "price": 4.99, "description": "Smooth ice cream with Chikoo (sapota) flavor.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Kesar Pista Ice Cream", "price": 5.49, "description": "Saffron and pistachio-flavored ice cream.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Tender Coconut Sundae", "price": 6.49, "description": "Sundae topped with tender coconut ice cream and toppings.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Rose Ice Cream", "price": 4.99, "description": "Fragrant ice cream with rose flavor.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Kesar Malai Ice Cream", "price": 5.49, "description": "Rich ice cream with saffron and malai (cream).", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Anjeer Ice Cream", "price": 5.49, "description": "Ice cream with the goodness of dried figs (anjeer).", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Mango Mastani", "price": 6.99, "description": "A delightful blend of mango ice cream and mango pulp.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Gulkand Ice Cream", "price": 5.49, "description": "Ice cream with the sweetness of Gulkand (rose petal jam).", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Anjeer Badam Kulfi", "price": 6.49, "description": "Traditional Indian frozen dessert with figs and almonds.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Black Currant Ice Cream", "price": 4.99, "description": "Berry-flavored ice cream with black currants.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Kesar Malai Kulfi", "price": 6.49, "description": "Creamy saffron-flavored Indian frozen dessert.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Belgium Chocolate Ice Cream", "price": 5.99, "description": "Decadent ice cream with rich Belgium chocolate.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "9",
  "name": "Theobroma",
      "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/a2ste667zw0ms1fjrnb2",
  coverimage:"https://res.cloudinary.com/purnesh/image/upload/w_540,f_auto/theoo.jpg",
  "locality": "Grand Avenue",
  "areaName": "West End",
  "rating": 4.8,
  "timeToDeliver": 30,
  "menu": [
    { "id": 1, "item_name": "Chocolate Truffle Cake", "price": 6.99, "description": "Rich and velvety chocolate truffle cake.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Red Velvet Cupcake", "price": 3.49, "description": "Moist and delicious red velvet cupcake.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Blueberry Cheesecake", "price": 5.99, "description": "Creamy cheesecake with blueberry topping.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Nutella Brownie", "price": 4.99, "description": "Fudgy brownie with Nutella swirls.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Strawberry Mousse", "price": 4.49, "description": "Light and fluffy strawberry mousse.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Chocolate Chip Cookie", "price": 2.49, "description": "Classic cookie with chocolate chips.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Blueberry Danish", "price": 3.99, "description": "Buttery Danish pastry with blueberry filling.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Apple Crumble Pie", "price": 5.49, "description": "Warm apple pie with crumbly topping.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Carrot Cake Slice", "price": 4.99, "description": "Spiced carrot cake with cream cheese frosting.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Chocolate Eclair", "price": 3.49, "description": "Light and fluffy pastry filled with chocolate cream.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Blueberry Muffin", "price": 3.49, "description": "Moist muffin with bursts of blueberries.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Raspberry White Chocolate Tart", "price": 4.99, "description": "Tart with raspberry and white chocolate filling.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Banana Walnut Loaf", "price": 4.99, "description": "Nutty loaf with ripe bananas and walnuts.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Black Forest Pastry", "price": 4.99, "description": "Pastry with layers of chocolate and cherries.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Hazelnut Praline Cake", "price": 5.99, "description": "Cake with hazelnut praline frosting.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "10",
  "name": "The Burger Club",
      "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/d96267738c19ec62acb5390e52faba41",
  coverimage:"https://imageproxy.wolt.com/venue/621decd1e58866fed2c30984/dce26a32-9aed-11ec-afee-4eff19176a04___the_burger_club_cover_2.jpg",
  "locality": "Oak Street",
  "areaName": "East End",
  "rating": 4.4,
  "timeToDeliver": 20,
  "menu": [
    { "id": 1, "item_name": "Classic Beef Burger", "price": 7.99, "description": "Juicy beef patty with lettuce, tomatoes, and onions.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Cheeseburger", "price": 8.49, "description": "Beef burger with melted cheese and toppings.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "BBQ Bacon Burger", "price": 8.99, "description": "Beef burger with BBQ sauce and bacon.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Mushroom Swiss Burger", "price": 8.49, "description": "Beef burger with sautéed mushrooms and Swiss cheese.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Crispy Chicken Burger", "price": 7.99, "description": "Crispy chicken fillet with lettuce and mayo.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Spicy Veggie Burger", "price": 7.49, "description": "Spicy vegetarian burger with fresh veggies.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Turkey Burger", "price": 8.99, "description": "Juicy turkey patty with lettuce and tomatoes.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Double Cheeseburger", "price": 9.99, "description": "Double beef patties with melted cheese.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Avocado Chicken Burger", "price": 8.99, "description": "Grilled chicken with avocado and mayo.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Portobello Mushroom Burger", "price": 8.49, "description": "Grilled Portobello mushroom with Swiss cheese.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Beyond Meat Burger", "price": 9.49, "description": "Plant-based Beyond Meat burger with toppings.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Fish Fillet Burger", "price": 8.99, "description": "Breaded fish fillet with tartar sauce.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Southwest Chicken Burger", "price": 8.49, "description": "Grilled chicken with Southwest sauce and veggies.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Vegan Chickpea Burger", "price": 8.49, "description": "Vegan burger made with chickpeas and spices.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Teriyaki Salmon Burger", "price": 9.99, "description": "Grilled salmon patty with teriyaki glaze.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "11",
  "name": "Behrouz Biryani - Royal & Safe",
      "cloudinaryImageId": "https://images.jdmagicbox.com/comp/mumbai/a4/022pxx22.xx22.190116192626.v2a4/catalogue/behrouz-biryani-kandivali-east-mumbai-biryani-delivery-restaurants-7df2lc18a8.jpg",
  coverimage:"https://www.socialsamosa.com/wp-content/uploads/2018/06/Behrouz-Biryani-Story.jpg",
  "locality": "Heritage Lane",
  "areaName": "Old Town",
  "rating": 4.5,
  "timeToDeliver": 35,
  "menu": [
    { "id": 1, "item_name": "Chicken Biryani", "price": 11.99, "description": "Flavorful biryani with tender chicken pieces.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Mutton Biryani", "price": 13.49, "description": "Authentic biryani with succulent mutton.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Veg Biryani", "price": 10.99, "description": "Delicious biryani with assorted vegetables.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Paneer Biryani", "price": 11.49, "description": "Biryani with flavorful paneer (cottage cheese).", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Egg Biryani", "price": 10.99, "description": "Biryani with boiled eggs and spices.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Chicken Kebab Biryani", "price": 12.49, "description": "Biryani with succulent chicken kebabs.", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Fish Biryani", "price": 12.49, "description": "Biryani with flavorful fish pieces.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Hyderabadi Biryani", "price": 12.99, "description": "Authentic Hyderabadi biryani with your choice of meat.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Dum Gosht Biryani", "price": 13.99, "description": "Slow-cooked biryani with succulent meat.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Keema Biryani", "price": 12.49, "description": "Biryani with flavorful minced meat.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Lucknowi Biryani", "price": 12.99, "description": "Biryani with Lucknowi spices and meat of your choice.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Chicken Tikka Biryani", "price": 12.49, "description": "Biryani with succulent chicken tikka pieces.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Ambur Biryani", "price": 12.99, "description": "Biryani with the traditional flavors of Ambur.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Keema Egg Biryani", "price": 12.99, "description": "Biryani with minced meat and boiled eggs.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Subz-e-Biryani", "price": 10.99, "description": "Vegetable biryani with aromatic spices.", "image": "item_image_url_here" }
  ]
    },
    {
  "id": "12",
  "name": "Wow! Momo",
  "cloudinaryImageId": "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/4e093cbd10bcd8ceff3faefb8fbdf258",
      "locality": "Market Square",
  coverimage:"https://sugermint.com/wp-content/uploads/2020/02/Wow-Momos-1.jpg",
  "areaName": "Central Square",
  "rating": 4.3,
  "timeToDeliver": 15,
  "menu": [
    { "id": 1, "item_name": "Steamed Chicken Momo", "price": 4.99, "description": "Delicious momo filled with chicken.", "image": "item_image_url_here" },
    { "id": 2, "item_name": "Fried Chicken Momo", "price": 5.49, "description": "Crispy momo with fried chicken filling.", "image": "item_image_url_here" },
    { "id": 3, "item_name": "Steamed Veg Momo", "price": 4.49, "description": "Healthy momo filled with assorted vegetables.", "image": "item_image_url_here" },
    { "id": 4, "item_name": "Pan-Fried Veg Momo", "price": 4.99, "description": "Momo with a crispy pan-fried outer layer and veg filling.", "image": "item_image_url_here" },
    { "id": 5, "item_name": "Tandoori Chicken Momo", "price": 5.49, "description": "Momo with a delicious tandoori chicken filling.", "image": "item_image_url_here" },
    { "id": 6, "item_name": "Steamed Paneer Momo", "price": 4.99, "description": "Soft momo filled with paneer (cottage cheese).", "image": "item_image_url_here" },
    { "id": 7, "item_name": "Fried Paneer Momo", "price": 5.49, "description": "Crispy momo with fried paneer filling.", "image": "item_image_url_here" },
    { "id": 8, "item_name": "Steamed Chocolate Momo", "price": 4.99, "description": "Sweet momo filled with chocolate.", "image": "item_image_url_here" },
    { "id": 9, "item_name": "Fried Chocolate Momo", "price": 5.49, "description": "Crispy momo with a gooey chocolate filling.", "image": "item_image_url_here" },
    { "id": 10, "item_name": "Steamed Chicken Sausage Momo", "price": 5.49, "description": "Momo with chicken sausage filling.", "image": "item_image_url_here" },
    { "id": 11, "item_name": "Schezwan Chicken Momo", "price": 5.49, "description": "Momo with spicy Schezwan chicken filling.", "image": "item_image_url_here" },
    { "id": 12, "item_name": "Cheese Corn Momo", "price": 4.99, "description": "Momo with creamy cheese and corn filling.", "image": "item_image_url_here" },
    { "id": 13, "item_name": "Fried Schezwan Veg Momo", "price": 4.99, "description": "Crispy momo with spicy Schezwan veg filling.", "image": "item_image_url_here" },
    { "id": 14, "item_name": "Prawn Momo", "price": 5.99, "description": "Delicious momo with prawn filling.", "image": "item_image_url_here" },
    { "id": 15, "item_name": "Steamed Momo Combo (Assorted)", "price": 9.99, "description": "Combo with an assortment of steamed momo.", "image": "item_image_url_here" }
  ]
}












]